/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_xzq_jnitest_JniTools */

#ifndef _Included_com_xzq_jnitest_JniTools
#define _Included_com_xzq_jnitest_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    init
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_xzq_jnitest_JniTools_init__
        (JNIEnv *, jobject);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    init
 * Signature: (I)V
 */
extern "C" JNIEXPORT void JNICALL Java_com_xzq_jnitest_JniTools_init__I
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_com_xzq_jnitest_JniTools_init__Ljava_lang_String_2
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    update
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_xzq_jnitest_JniTools_update
        (JNIEnv *, jobject);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    add
 * Signature: (II)I
 */
extern "C" JNIEXPORT jint JNICALL Java_com_xzq_jnitest_JniTools_add
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    sub
 * Signature: (II)I
 */
extern "C" JNIEXPORT jint JNICALL Java_com_xzq_jnitest_JniTools_sub
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    mul
 * Signature: (II)I
 */
extern "C" JNIEXPORT jint JNICALL Java_com_xzq_jnitest_JniTools_mul
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    div
 * Signature: (II)I
 */
extern "C" JNIEXPORT jint JNICALL Java_com_xzq_jnitest_JniTools_div
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    testException
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_xzq_jnitest_JniTools_testException
        (JNIEnv *, jobject);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    testArray
 * Signature: ([I[Ljava/lang/String;)[I
 */
extern "C" JNIEXPORT jintArray JNICALL Java_com_xzq_jnitest_JniTools_testArray
        (JNIEnv *, jobject, jintArray, jobjectArray);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    fun1
 * Signature: ()Ljava/lang/String;
 */
extern "C" JNIEXPORT jstring JNICALL Java_com_xzq_jnitest_JniTools_fun1
        (JNIEnv *, jclass);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
extern "C" JNIEXPORT jobject JNICALL Java_com_xzq_jnitest_JniTools_getIntegerObject
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    manipulationStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
extern "C" JNIEXPORT jstring JNICALL Java_com_xzq_jnitest_JniTools_manipulationStr
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    testCallJava
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_xzq_jnitest_JniTools_testCallJava
        (JNIEnv *, jobject);

/*
 * Class:     com_xzq_jnitest_JniTools
 * Method:    testExceptionNotCrash
 * Signature: (I)Ljava/lang/String;
 */
extern "C" JNIEXPORT jstring JNICALL Java_com_xzq_jnitest_JniTools_testExceptionNotCrash
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif